name: build

env:
  HOMEBREW_NO_INSTALL_CLEANUP: 1
  CTEST_NO_TESTS_ACTION: error
  FC: gfortran-13
  CTEST_PARALLEL_LEVEL: 4
  CMAKE_BUILD_PARALLEL_LEVEL: 4


on:
  push:
    paths:
      - "scripts/CMakeLists.txt"
      - "cmake/libraries.json"
      - ".github/workflows/ci_build.yml"

jobs:

  linux_mac:
    timeout-minutes: 20

    strategy:
      matrix:
        os: [ubuntu-latest]
        shared: [true, false]
        include:
        - os: macos-latest
          shared: false

    runs-on: ${{ matrix.os}}

    steps:
    - uses: actions/checkout@v4

    - name: Configure HDF5 library
      run: >-
        cmake
        -S scripts -B scripts/build
        --install-prefix ${{ runner.temp }}
        -DBUILD_SHARED_LIBS:BOOL=${{ matrix.shared }}

    - name: Build/install HDF5
      run: cmake --build scripts/build

    - name: configure h5fortran
      run: >-
        cmake --preset default
        --install-prefix ${{ runner.temp }}
        -DBUILD_SHARED_LIBS:BOOL=${{ matrix.shared }}
        -DCMAKE_PREFIX_PATH=${{ runner.temp }}

    - name: build / test h5fortran
      run: cmake --workflow --preset default

    - name: install h5fortran
      run: cmake --install build

    - name: example workflow
      run: cmake -S example -B example/build -DCMAKE_PREFIX_PATH=${{ runner.temp }}

    - run: cmake --build example/build

    - run: ctest --test-dir example/build -V
